### ISSUE TITLE
No results when get.all and there is only the current state

### ISSUE THREAD

**Issue by albertodeste** [h-omer/neo4j-graph-versioner#2]
There is an unwanted behavior while retrieving all the states connected to the entity when the entity has only the "current" state associated to it.

**Steps to reproduce**

- Starting from an empty database
- Run `CALL graph.versioner.init('Person', {ssn: 123456789, name: 'Marco'}, {address: 'Via Roma 11'})`
- Run `MATCH (p:Person) WITH p CALL graph.versioner.get.all(p) YIELD path RETURN path`

**Current Behaviour**

There are no results

**Comment by mfalcier** [comment]
It's a bug.
It will be fixed on the next commit, and the `graph.versioner.get.all` procedure will also return the Entity node. This way, a path will be always returned, at its minimum, `(:Entity)-[:CURRENT]->(:State)` in other cases `(:Entity)-[:CURRENT]->(:State)-[:PREVIOUS*]->(:State)`.
